zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    book-catalog-service:
      path: /rest/**
      serviceId: BOOKCATALOGSERVICE
    book-info-service:
      path: /info/**
      serviceId: BOOKINFOSERVICE
    book-rating-service:
       path: /rating/**
       serviceId: BOOKRATINGSERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-server
    
# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000